export const VENUES = [
  {
    id: 'v1',
    name: 'Sala El Sol',
    address: 'C/ Jardines, 3',
    neighborhood: 'Malasaña',
    capacity: 250,
    website: 'https://www.elsol-madrid.com',
    description: 'Sala histórica del Madrid de la Movida. Referente indie y pop desde 1979.',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80',
  },
  {
    id: 'v2',
    name: 'La Riviera',
    address: 'Paseo Bajo de la Virgen del Puerto, s/n',
    neighborhood: 'Arganzuela',
    capacity: 2500,
    website: 'https://salariviera.com',
    description: 'Gran sala junto al río Manzanares. Programación de rock y pop nacional e internacional.',
    image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&q=80',
  },
  {
    id: 'v3',
    name: 'WiZink Center',
    address: 'Av. de Felipe II, s/n',
    neighborhood: 'Retiro',
    capacity: 15000,
    website: 'https://www.wizinkcenter.es',
    description: 'El pabellón de referencia en Madrid para los grandes conciertos nacionales e internacionales.',
    image: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80',
  },
  {
    id: 'v4',
    name: 'Moby Dick Club',
    address: 'Av. de Brasil, 5',
    neighborhood: 'Azca',
    capacity: 400,
    website: 'https://mobydickclub.com',
    description: 'Local de rock clásico y emergente en el corazón empresarial de Madrid.',
    image: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800&q=80',
  },
  {
    id: 'v5',
    name: 'Café Central',
    address: 'Plaza del Ángel, 10',
    neighborhood: 'Sol / Huertas',
    capacity: 100,
    website: 'https://cafecentralmadrid.com',
    description: 'Uno de los mejores clubs de jazz del mundo según DownBeat. Ambiente íntimo e imprescindible.',
    image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80',
  },
  {
    id: 'v6',
    name: 'Sala Copérnico',
    address: 'C/ Galileo, 26',
    neighborhood: 'Chamberí',
    capacity: 700,
    website: '',
    description: 'Sala polivalente en Chamberí con excelente acústica y programación de rock, pop e indie.',
    image: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&q=80',
  },
  {
    id: 'v7',
    name: 'Sala Caracol',
    address: 'C/ Bernardino Obregón, 18',
    neighborhood: 'Embajadores',
    capacity: 500,
    website: '',
    description: 'Sala underground de referencia en Madrid. Apuesta por bandas emergentes y géneros alternativos.',
    image: 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=800&q=80',
  },
]

export const EVENTS = [
  {
    id: 'e1', venue_id: 'v2',
    title: 'Mon Laferte en Madrid',
    artist: 'Mon Laferte',
    date: '2026-06-15', time: '21:00', price: 35,
    genre: 'Pop Latino',
    description: 'La cantautora chilena regresa a Madrid con su gira más íntima y personal, presentando su último álbum. Una noche de emociones y grandes canciones.',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
  },
  {
    id: 'e2', venue_id: 'v3',
    title: 'Izal — Gira de Despedida',
    artist: 'Izal',
    date: '2026-06-20', time: '20:00', price: 45,
    genre: 'Indie Rock',
    description: 'El grupo madrileño se despide de los escenarios con una noche histórica en el WiZink Center. El broche de oro a una carrera brillante.',
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80',
  },
  {
    id: 'e3', venue_id: 'v2',
    title: 'Vetusta Morla — 20 Años',
    artist: 'Vetusta Morla',
    date: '2026-06-28', time: '21:30', price: 40,
    genre: 'Indie Rock',
    description: 'Celebración de dos décadas de trayectoria con un show especial que repasa todos sus álbumes. Un acontecimiento para el indie español.',
    image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80',
  },
  {
    id: 'e4', venue_id: 'v7',
    title: 'Sidecars en Caracol',
    artist: 'Sidecars',
    date: '2026-07-01', time: '21:00', price: 18,
    genre: 'Rock',
    description: 'Los madrileños presentan su nuevo EP en formato pequeño y cercano, en su sala de siempre.',
    image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80',
  },
  {
    id: 'e5', venue_id: 'v1',
    title: 'Rufus T. Firefly',
    artist: 'Rufus T. Firefly',
    date: '2026-07-05', time: '22:00', price: 15,
    genre: 'Indie Pop',
    description: 'Noche de pop indie y melodías pegadizas en la mítica Sala El Sol. Uno de los grupos emergentes más interesantes del momento.',
    image: 'https://images.unsplash.com/photo-1571266028243-d220c6a7ee7c?w=800&q=80',
  },
  {
    id: 'e6', venue_id: 'v6',
    title: 'Coque Malla — Acústico',
    artist: 'Coque Malla',
    date: '2026-07-08', time: '21:00', price: 25,
    genre: 'Rock / Cantautor',
    description: 'El ex-Los Ronaldos presenta un set íntimo en Copérnico. Canciones nuevas, clásicos y mucho corazón.',
    image: 'https://images.unsplash.com/photo-1519683109079-d5f539e1542f?w=800&q=80',
  },
  {
    id: 'e7', venue_id: 'v4',
    title: 'Viva Suecia',
    artist: 'Viva Suecia',
    date: '2026-07-12', time: '21:00', price: 20,
    genre: 'Rock',
    description: 'Los murcianos traen su rock directo y sin filtros a Moby Dick, uno de sus locales favoritos de Madrid.',
    image: 'https://images.unsplash.com/photo-1534258936925-c58bed479fcb?w=800&q=80',
  },
  {
    id: 'e8', venue_id: 'v5',
    title: 'Jazzuela Quartet',
    artist: 'Jazzuela Quartet',
    date: '2026-07-15', time: '21:30', price: 12,
    genre: 'Jazz',
    description: 'Cuarteto de jazz contemporáneo con influencias latinas. Una noche de improvisación en el mítico Café Central.',
    image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80',
  },
  {
    id: 'e9', venue_id: 'v3',
    title: 'C. Tangana — El Regreso',
    artist: 'C. Tangana',
    date: '2026-07-20', time: '21:00', price: 55,
    genre: 'Urban / Pop',
    description: 'Pucho vuelve al WiZink con su espectáculo más ambicioso. Una producción visual y musical sin igual.',
    image: 'https://images.unsplash.com/photo-1499364615650-ec38552f4f34?w=800&q=80',
  },
  {
    id: 'e10', venue_id: 'v2',
    title: 'Amaia — Tour Pero No Pasa Nada',
    artist: 'Amaia',
    date: '2026-07-25', time: '21:00', price: 30,
    genre: 'Indie Pop',
    description: 'La navarra presenta su nueva era con todo el encanto y naturalidad que la convirtieron en un fenómeno del pop español.',
    image: 'https://images.unsplash.com/photo-1483872788346-c0b5e3e6e2bb?w=800&q=80',
  },
  {
    id: 'e11', venue_id: 'v1',
    title: 'Hinds',
    artist: 'Hinds',
    date: '2026-08-02', time: '22:00', price: 22,
    genre: 'Indie Rock',
    description: 'Las madrileñas vuelven a casa para presentar su último trabajo. Energía, carisma y rock sin concesiones.',
    image: 'https://images.unsplash.com/photo-1501386761578-eaa54b912b97?w=800&q=80',
  },
  {
    id: 'e12', venue_id: 'v6',
    title: 'Leiva — Acústico',
    artist: 'Leiva',
    date: '2026-08-08', time: '21:00', price: 28,
    genre: 'Rock',
    description: 'El ex-Pereza presenta un show íntimo que recorre toda su carrera en solitario con guitarra y voz.',
    image: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800&q=80',
  },
]

export const GENRES = [...new Set(EVENTS.map(e => e.genre))].sort()
